[package]
authors = ["Konstantin Stepanov <me@kstep.me>"]
description = "ArchLinux's PKGBULD generator from Cargo.toml manifest file"
homepage = "https://github.com/kstep/cargo-pkgbuild"
license = "MIT/Apache-2.0"
name = "cargo-pkgbuild"
readme = "README.md"
version = "0.1.1"

[dependencies]
cargo = "0.11.0"
rustc-serialize = "0.3.19"
toml = "0.1.30"
